Repository wecode-bootcamp-korea/41-backend-westagram-1, pull requests merged in 2022-12, with the labels that each got.

#4 [41기 김승기] Assignment 1 | Westagram Backend Project - Express 초기 환경세팅
  seungki/.env.sample
  seungki/.gitignore
  seungki/app.js
  seungki/package-lock.json
  seungki/package.json
Labels: 완료

#2 [41기 류건호] Assignment 1 | Westagram Backend Project - Express 초기 환경세팅
  package-lock.json
  package.json
  ryugunho/.env.sample
  ryugunho/.gitignore
  ryugunho/app.js
  ryugunho/db/migrations/20221220113309_create_user_table.sql
  ryugunho/db/migrations/20221220113346_create_post_table.sql
  ryugunho/db/migrations/20221220113653_create_userPost_table.sql
  ryugunho/package-lock.json
  ryugunho/package.json
Labels: 멘토 리뷰 요청

#8 [41기 김승기] Assignment 2 | Westagram Backend Project - 유저 회원가입 하기
  seungki/.gitignore
  seungki/app.js
  seungki/db/migrations/20221221235847_create_users_table.sql
  seungki/db/migrations/20221221235854_create_posts_table.sql
Labels: 완료

#5 [41기 류건호] Assignment 2: Express API - 유저 회원가입 하기
  ryugunho/.gitignore
  ryugunho/app.js
  ryugunho/db/migrations/20221220113309_create_user_table.sql
  ryugunho/db/migrations/20221220113346_create_post_table.sql
Labels: Conflict 해결 요청

#9 [41기 심예윤] Assignment 1 : Express API - 초기 환경 세팅
  yeyun/.env.sample
  yeyun/.gitignore
  yeyun/app.js
  yeyun/package-lock.json
  yeyun/package.json
Labels: 멘토 리뷰 요청

#13 [41기 김승기] Assignment 3: Express API - CRUD 구현
  seungki/.env.sample
  seungki/app.js
  seungki/db/migrations/20221223050345_create_users_table.sql
  seungki/db/migrations/20221223050523_create_posts_table.sql
  seungki/db/migrations/20221223050752_create_likes_table.sql
  seungki/package-lock.json
Labels: Conflict 해결 요청

#10 [41기 김승] Assignment 1 : Express API - 초기 환경 세팅
  5EUNG/.env.sample
  5EUNG/.gitignore
  5EUNG/app.js
  5EUNG/package-lock.json
  5EUNG/package.json
Labels: 멘토 리뷰 요청

#11 [41기 박상우] Assignment 1: Express API - 초기 환경 세팅
  sangwoo/.env sample
  sangwoo/.gitignore
  sangwoo/app.js
  sangwoo/package-lock.json
  sangwoo/package.json
Labels: 멘토 리뷰 요청

#12 [41기 심예윤 Assignment 2 : Express API - 유저 회원 가입]
  5EUNG/.env.sample
  5EUNG/.gitignore
  5EUNG/app.js
  5EUNG/package-lock.json
  5EUNG/package.json
  gildong/.gitignore
  gildong/package.json
  ryugunho/.env.sample
  ryugunho/.gitignore
  ryugunho/app.js
  ryugunho/db/migrations/20221220113309_create_user_table.sql
  ryugunho/db/migrations/20221220113346_create_post_table.sql
  ryugunho/db/migrations/20221220113653_create_userPost_table.sql
  ryugunho/db/migrations/20221221124100_create_table_likes.sql
  ryugunho/package-lock.json
  ryugunho/package.json
  sangwoo/.env sample
  sangwoo/.gitignore
  sangwoo/app.js
  sangwoo/package-lock.json
  sangwoo/package.json
  seungki/.env.sample
  seungki/.gitignore
  seungki/app.js
  seungki/db/migrations/20221221235847_create_users_table.sql
  seungki/db/migrations/20221221235854_create_posts_table.sql
  seungki/db/migrations/20221223050345_create_users_table.sql
  seungki/db/migrations/20221223050523_create_posts_table.sql
  seungki/db/migrations/20221223050752_create_likes_table.sql
  seungki/package-lock.json
  seungki/package.json
  yeyun/.gitignore
  yeyun/app.js
  yeyun/db/migrations/20221223062339_create_users_table.sql
  yeyun/db/migrations/20221223062359_create_posts_table.sql
  yeyun/db/migrations/20221226020335_create_likes_table.sql
Labels: Conflict 해결 요청

#23 [41기 김승기] Westagram Backend Project - Bcrypt를 이용하여 비밀번호 암호화하기
  seungki/app.js
  seungki/middleware/auth.js
  seungki/package-lock.json
  seungki/package.json
Labels: Conflict 해결 요청

#22 [41기 류건호] Westagram Backend Project - jwt Token 발행
  .gitignore
  ryugunho/app.js
  ryugunho/package-lock.json
  ryugunho/package.json
Labels: Conflict 해결 요청

#19 [41기 김승] Assignment 2 : Express API - 유저 회원가입 하기
  5EUNG/app.js
Labels: 멘토 리뷰 요청

#24 [41기 김승기]Westagram Backend Project - Bcrypt Verification 및 JWT 발급하기
  seungki/app.js
  seungki/package-lock.json
  seungki/package.json
Labels: 멘토 리뷰 요청

#29 [41기 김승기] Westagram Backend Project - 로그인 한 사용자만 게시글 등록하기
  seungki/app.js
Labels: 멘토 리뷰 요청

#30 [41기 김승] Westagram Backend Project - Bcrypt를 이용하여 비밀번호 암호화하기
  5EUNG/app.js
Labels: 멘토 리뷰 요청

#31 [41기 류건호] Westagram Backend Project -bcryt를 이용한 비밀번호 암호화
  ryugunho/.gitignore
  ryugunho/app.js
Labels: 멘토 리뷰 요청

#32 [41기 류건호] Westagram Backend Project -post 등록전 토큰 확인
  ryugunho/app.js
  ryugunho/token.js
Labels: 멘토 리뷰 요청

#33 [41기 심예윤] Westagram Backend Project - Bcrypt를 이용하여 비밀번호 암호화하기
  ryugunho/app.js
  yeyun/.gitignore
  yeyun/app.js
  yeyun/db/migrations/20221223062359_create_posts_table.sql
  yeyun/db/migrations/20221228123729_create_likes_table.sql
  yeyun/package-lock.json
  yeyun/package.json
Labels: Conflict 해결 요청

#25 [41기 김승]Assignment 3 : Express API - CRUD
  5EUNG/app.js
  5EUNG/db/migrations/20221226113028_users.sql
  5EUNG/db/migrations/20221226114056_posts.sql
  5EUNG/db/migrations/20221226134705_likes.sql
  5EUNG/package-lock.json
  5EUNG/package.json
Labels: 멘토 리뷰 요청

#34 [41기 김승]Westagram Backend Project - Bcrypt Verification 및 JWT 발급하기
  5EUNG/.env.sample
  5EUNG/app.js
Labels: 멘토 리뷰 요청

#36 [41기 김승기] RESTful API url 변경 및 콘솔에러 추가
  seungki/app.js
Labels: 멘토 리뷰 요청

#37 [41기 박상우] Westagram Backend Project - Bcrypt를 이용하여 비밀번호 암호화하기
  sangwoo/app.js
  sangwoo/db/migrations/20221229040706_create_users_table.sql
  sangwoo/package-lock.json
  sangwoo/package.json
Labels: 멘토 리뷰 요청
